name: Deploy

on:
  workflow_dispatch

jobs:

  deploy:
    runs-on: "${{ vars.OS_NAME }}"

    steps:
      - uses: actions/checkout@v3

      # Install ssh key
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2.3.1
        with:
          key: "${{ secrets.OPENSSH_PRIVATE_KEY }}"
          known_hosts: "just-a-placeholder-so-we-dont-get-errors"
          
      - name: Generate auth hosts
        run: ssh-keyscan -H ${{ vars.SERVER_HOST }} >> ~/.ssh/known_hosts

      - name: Update project files
      - run: rsync --archive --compress --progress . ${{ vars.SERVER_USER }}@${{ vars.SERVER_HOST }}:${{ vars.SERVER_PATH }}

      - name: Create config.ini
      - run: ssh "${{ vars.SERVER_USER }}@${{ vars.SERVER_HOST }}" "echo \"${{ vars.CONFIG_INI }}\" > ${{ vars.SERVER_PATH }}/config.ini"

      - name: Restart the service
      - run: ssh "${{ vars.SERVER_USER }}@${{ vars.SERVER_HOST }}" "systemctl restart ${{ vars.SERVICE_NAME }}"
